In [1]:
import pandas as pd

In [2]:
d=pd.read_csv("Salary_Data.csv")
d

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0
6703,26.0,Female,High School,Sales Executive,1.0,35000.0

In [3]:
d.columns

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'],
      dtype='object')

In [4]:
d.columns[d.isnull().any()]

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'],
      dtype='object')

In [5]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   float64
 1   Gender               6702 non-null   object
 2   Education Level      6701 non-null   object
 3   Job Title            6702 non-null   object
 4   Years of Experience  6701 non-null   float64
 5   Salary               6699 non-null   float64
dtypes: float64(3), object(3)
memory usage: 314.4+ KB

In [6]:
d=d.drop(["Education Level"],axis=1)
d

       Age  Gender              Job Title  Years of Experience    Salary
0     32.0    Male      Software Engineer                  5.0   90000.0
1     28.0  Female           Data Analyst                  3.0   65000.0
2     45.0    Male         Senior Manager                 15.0  150000.0
3     36.0  Female        Sales Associate                  7.0   60000.0
4     52.0    Male               Director                 20.0  200000.0
...    ...     ...                    ...                  ...       ...
6699  49.0  Female  Director of Marketing                 20.0  200000.0
6700  32.0    Male        Sales Associate                  3.0   50000.0
6701  30.0  Female      Financial Manager                  4.0   55000.0
6702  46.0    Male      Marketing Manager                 14.0  140000.0
6703  26.0  Female        Sales Executive                  1.0   35000.0

[6704 rows x 5 columns]

In [7]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   float64
 1   Gender               6702 non-null   object
 2   Job Title            6702 non-null   object
 3   Years of Experience  6701 non-null   float64
 4   Salary               6699 non-null   float64
dtypes: float64(3), object(2)
memory usage: 262.0+ KB

In [8]:
d["Gender"].value_counts()

Gender
Male      3674
Female    3014
Other       14
Name: count, dtype: int64

In [9]:
d["Job Title"].value_counts()

Job Title
Software Engineer             518
Data Scientist                453
Software Engineer Manager     376
Data Analyst                  363
Senior Project Engineer       318
                             ...
Account Manager                 1
Help Desk Analyst               1
Senior Training Specialist      1
Junior Web Designer             1
Supply Chain Analyst            1
Name: count, Length: 193, dtype: int64

In [10]:
d["Job Title"].values

array(['Software Engineer', 'Data Analyst', 'Senior Manager', ...,
       'Financial Manager', 'Marketing Manager', 'Sales Executive'],
      shape=(6704,), dtype=object)

In [11]:
# r=[]
# for i in d["Job Title"]:
#     r.append(i)
# print(r)

In [12]:
# d=set(r)
# d

In [13]:
e=pd.get_dummies(d["Gender"])
e

      Female   Male  Other
0      False   True  False
1       True  False  False
2      False   True  False
3       True  False  False
4      False   True  False
...      ...    ...    ...
6699    True  False  False
6700   False   True  False
6701    True  False  False
6702   False   True  False
6703    True  False  False

[6704 rows x 3 columns]

In [14]:
d=pd.concat([d,e],axis=1)
d

,Age,Gender,Job Title,Years of Experience,Salary,Female,Male,Other
0,32.0,Male,Software Engineer,5.0,90000.0,False,True,False
1,28.0,Female,Data Analyst,3.0,65000.0,True,False,False
2,45.0,Male,Senior Manager,15.0,150000.0,False,True,False
3,36.0,Female,Sales Associate,7.0,60000.0,True,False,False
4,52.0,Male,Director,20.0,200000.0,False,True,False
...,...,...,...,...,...,...,...,...
6699,49.0,Female,Director of Marketing,20.0,200000.0,True,False,False
6700,32.0,Male,Sales Associate,3.0,50000.0,False,True,False
6701,30.0,Female,Financial Manager,4.0,55000.0,True,False,False
6702,46.0,Male,Marketing Manager,14.0,140000.0,False,True,False
6703,26.0,Female,Sales Executive,1.0,35000.0,True,False,False

In [15]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   float64
 1   Gender               6702 non-null   object
 2   Job Title            6702 non-null   object
 3   Years of Experience  6701 non-null   float64
 4   Salary               6699 non-null   float64
 5   Female               6704 non-null   bool
 6   Male                 6704 non-null   bool
 7   Other                6704 non-null   bool
dtypes: bool(3), float64(3), object(2)
memory usage: 281.6+ KB

In [16]:
d=d.drop(["Gender"],axis=1)
d

,Age,Job Title,Years of Experience,Salary,Female,Male,Other
0,32.0,Software Engineer,5.0,90000.0,False,True,False
1,28.0,Data Analyst,3.0,65000.0,True,False,False
2,45.0,Senior Manager,15.0,150000.0,False,True,False
3,36.0,Sales Associate,7.0,60000.0,True,False,False
4,52.0,Director,20.0,200000.0,False,True,False
...,...,...,...,...,...,...,...
6699,49.0,Director of Marketing,20.0,200000.0,True,False,False
6700,32.0,Sales Associate,3.0,50000.0,False,True,False
6701,30.0,Financial Manager,4.0,55000.0,True,False,False
6702,46.0,Marketing Manager,14.0,140000.0,False,True,False
6703,26.0,Sales Executive,1.0,35000.0,True,False,False

In [17]:
d["Years of Experience"]=d["Years of Experience"].fillna(d["Years of Experience"].mean())
d

,Age,Job Title,Years of Experience,Salary,Female,Male,Other
0,32.0,Software Engineer,5.0,90000.0,False,True,False
1,28.0,Data Analyst,3.0,65000.0,True,False,False
2,45.0,Senior Manager,15.0,150000.0,False,True,False
3,36.0,Sales Associate,7.0,60000.0,True,False,False
4,52.0,Director,20.0,200000.0,False,True,False
...,...,...,...,...,...,...,...
6699,49.0,Director of Marketing,20.0,200000.0,True,False,False
6700,32.0,Sales Associate,3.0,50000.0,False,True,False
6701,30.0,Financial Manager,4.0,55000.0,True,False,False
6702,46.0,Marketing Manager,14.0,140000.0,False,True,False
6703,26.0,Sales Executive,1.0,35000.0,True,False,False

In [18]:
d.columns[d.isna().any()]

Index(['Age', 'Job Title', 'Salary'], dtype='object')

In [19]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6704 entries, 0 to 6703
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   float64
 1   Job Title            6702 non-null   object
 2   Years of Experience  6704 non-null   float64
 3   Salary               6699 non-null   float64
 4   Female               6704 non-null   bool
 5   Male                 6704 non-null   bool
 6   Other                6704 non-null   bool
dtypes: bool(3), float64(3), object(1)
memory usage: 229.3+ KB

In [20]:
d["Salary"]=d["Salary"].fillna(d["Salary"].mean())
d

,Age,Job Title,Years of Experience,Salary,Female,Male,Other
0,32.0,Software Engineer,5.0,90000.0,False,True,False
1,28.0,Data Analyst,3.0,65000.0,True,False,False
2,45.0,Senior Manager,15.0,150000.0,False,True,False
3,36.0,Sales Associate,7.0,60000.0,True,False,False
4,52.0,Director,20.0,200000.0,False,True,False
...,...,...,...,...,...,...,...
6699,49.0,Director of Marketing,20.0,200000.0,True,False,False
6700,32.0,Sales Associate,3.0,50000.0,False,True,False
6701,30.0,Financial Manager,4.0,55000.0,True,False,False
6702,46.0,Marketing Manager,14.0,140000.0,False,True,False
6703,26.0,Sales Executive,1.0,35000.0,True,False,False

In [21]:
d.columns[d.isna().any()]

Index(['Age', 'Job Title'], dtype='object')

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x=d[["Years of Experience"]]
y=d["Salary"]

x_train,x_test,y_tarin,y_test = train_test_split(x,y,train_size=0.9,random_state=42)
x_train

      Years of Experience
1867                 15.0
865                   5.0
1760                  1.0
2184                  3.0
196                  11.0
...                   ...
3772                 12.0
5191                  3.0
5226                  3.0
5390                  4.0
860                   1.0

[6033 rows x 1 columns]

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
lr = LinearRegression()
lr.fit(x_train,y_tarin)

LinearRegression()

In [26]:
y_pred = lr.predict(x_test)
y_pred

array([192108.03567786, 114793.00035504,  79649.80248103,  72621.16290623,
        79649.80248103,  65592.52333143,  65592.52333143,  72621.16290623,
       142907.55865425, 100735.72120544,  93707.08163064, 121821.63992984,
       114793.00035504,  72621.16290623,  72621.16290623, 192108.03567786,
        79649.80248103, 135878.91907945, 156964.83780385, 114793.00035504,
       142907.55865425, 121821.63992984,  72621.16290623, 185079.39610306,
       107764.36078024,  72621.16290623, 100735.72120544,  65592.52333143,
        65592.52333143,  79649.80248103, 199136.67525266,  65592.52333143,
        65592.52333143, 121821.63992984,  65592.52333143, 171022.11695345,
        93707.08163064, 107764.36078024,  65592.52333143,  72621.16290623,
       121821.63992984, 248337.15227627, 142907.55865425, 149936.19822905,
        72621.16290623,  93707.08163064,  93707.08163064,  79649.80248103,
       142907.55865425,  86678.44205583,  79649.80248103,  65592.52333143,
       121821.63992984, 156964.83780385, 135878.91907945,  72621.16290623,
        72621.16290623, 121821.63992984, 192108.03567786, 192108.03567786,
        72621.16290623,  79649.80248103,  86678.44205583, 220222.59397707,
       185079.39610306, 135878.91907945,  93707.08163064,  79649.80248103,
        93707.08163064,  86678.44205583,  93707.08163064, 114793.00035504,
        72621.16290623, 149936.19822905, 100735.72120544,  72621.16290623,
        79649.80248103,  86678.44205583, 142907.55865425, 156964.83780385,
        86678.44205583, 114793.00035504, 128850.27950464, 142907.55865425,
       135878.91907945, 171022.11695345, 135878.91907945,  72621.16290623,
       107764.36078024,  93707.08163064, 156964.83780385,  79649.80248103,
       149936.19822905, 121821.63992984,  79649.80248103, 142907.55865425,
        86678.44205583, 121821.63992984, 128850.27950464,  72621.16290623,
        65592.52333143,  86678.44205583, 114793.00035504, 142907.55865425,
       156964.83780385,  93707.08163064,  72621.16290623, 149936.19822905,
       163993.47737865, 149936.19822905,  86678.44205583, 114793.00035504,
        65592.52333143,  86678.44205583,  72621.16290623,  93707.08163064,
       100735.72120544, 163993.47737865, 114793.00035504, 107764.36078024,
        79649.80248103,  72621.16290623,  93707.08163064,  79649.80248103,
       100735.72120544, 142907.55865425, 163993.47737865, 114793.00035504,
       149936.19822905, 142907.55865425, 121821.63992984, 199136.67525266,
        79649.80248103, 114793.00035504,  72621.16290623, 171022.11695345,
       206165.31482746,  86678.44205583, 114793.00035504,  72621.16290623,
        79649.80248103,  72621.16290623,  79649.80248103,  93707.08163064,
       121821.63992984,  79649.80248103,  79649.80248103,  86678.44205583,
       128850.27950464, 107764.36078024,  86678.44205583, 114793.00035504,
       135878.91907945,  86678.44205583, 142907.55865425,  79649.80248103,
        86678.44205583, 107764.36078024,  79649.80248103, 121821.63992984,
        65592.52333143, 142907.55865425, 213193.95440226, 262394.43142588,
        65592.52333143,  79649.80248103, 213193.95440226,  86678.44205583,
       192108.03567786, 107764.36078024,  65592.52333143, 156964.83780385,
        86678.44205583,  86678.44205583, 121821.63992984,  65592.52333143,
       213193.95440226, 128850.27950464, 171022.11695345,  86678.44205583,
       128850.27950464, 114793.00035504, 107764.36078024,  86678.44205583,
        58563.88375663,  65592.52333143,  72621.16290623, 135878.91907945,
       114793.00035504,  86678.44205583, 178050.75652826,  72621.16290623,
        65592.52333143, 114793.00035504, 156964.83780385, 135878.91907945,
        72621.16290623,  93707.08163064, 128850.27950464, 114793.00035504,
        58563.88375663, 121821.63992984,  86678.44205583, 234279.87312667,
       135878.91907945, 142907.55865425, 114793.00035504,  65592.52333143,
       185079.39610306, 171022.11695345, 178050.75652826,  86678.44205583,
       142907.55865425, 178050.75652826,  65592.52333143,  58563.88375663,
        79649.80248103,  79649.80248103,  86678.44205583,  72621.16290623,
        79649.80248103, 156964.83780385, 128850.27950464, 255365.79185108,
       128850.27950464, 100735.72120544,  58563.88375663,  86678.44205583,
        79649.80248103,  72621.16290623, 213193.95440226, 142907.55865425,
        79649.80248103, 206165.31482746,  79649.80248103, 121821.63992984,
       135878.91907945,  65592.52333143, 128850.27950464, 178050.75652826,
       114793.00035504,  72621.16290623, 114793.00035504,  72621.16290623,
       121821.63992984, 142907.55865425, 100735.72120544, 100735.72120544,
       178050.75652826, 114793.00035504, 114793.00035504,  65592.52333143,
       100735.72120544, 100735.72120544,  58563.88375663,  65592.52333143,
        72621.16290623, 121821.63992984,  65592.52333143, 100735.72120544,
        58563.88375663, 135878.91907945,  93707.08163064,  86678.44205583,
        86678.44205583, 185079.39610306, 178050.75652826,  72621.16290623,
       163993.47737865, 142907.55865425,  86678.44205583,  72621.16290623,
       276451.71057548,  65592.52333143, 135878.91907945, 114793.00035504,
       199136.67525266,  79649.80248103, 135878.91907945, 128850.27950464,
        72621.16290623,  65592.52333143, 142907.55865425,  72621.16290623,
        79649.80248103,  93707.08163064, 115458.52368144, 142907.55865425,
        79649.80248103,  79649.80248103, 107764.36078024,  86678.44205583,
       156964.83780385, 107764.36078024, 185079.39610306, 107764.36078024,
        79649.80248103,  65592.52333143,  79649.80248103, 121821.63992984,
        93707.08163064,  65592.52333143, 185079.39610306, 156964.83780385,
        79649.80248103, 107764.36078024,  65592.52333143, 100735.72120544,
       114793.00035504,  93707.08163064, 100735.72120544, 156964.83780385,
        72621.16290623, 185079.39610306,  86678.44205583,  58563.88375663,
       156964.83780385, 135878.91907945, 107764.36078024,  79649.80248103,
        79649.80248103,  93707.08163064, 163993.47737865, 142907.55865425,
       107764.36078024,  79649.80248103,  79649.80248103, 114793.00035504,
       171022.11695345,  86678.44205583,  65592.52333143, 149936.19822905,
       156964.83780385, 171022.11695345, 114793.00035504, 135878.91907945,
        86678.44205583, 156964.83780385,  86678.44205583, 135878.91907945,
        58563.88375663, 114793.00035504, 100735.72120544,  86678.44205583,
        86678.44205583,  72621.16290623, 128850.27950464,  93707.08163064,
        72621.16290623, 142907.55865425, 100735.72120544, 121821.63992984,
       185079.39610306, 100735.72120544,  93707.08163064,  86678.44205583,
       171022.11695345,  65592.52333143, 100735.72120544,  79649.80248103,
        72621.16290623, 107764.36078024, 171022.11695345,  79649.80248103,
        65592.52333143, 206165.31482746, 135878.91907945,  65592.52333143,
       156964.83780385, 206165.31482746, 128850.27950464, 149936.19822905,
        72621.16290623, 142907.55865425,  93707.08163064, 107764.36078024,
       100735.72120544, 128850.27950464, 149936.19822905,  86678.44205583,
        86678.44205583,  72621.16290623, 100735.72120544,  72621.16290623,
       178050.75652826,  93707.08163064,  65592.52333143, 156964.83780385,
        72621.16290623, 114793.00035504, 135878.91907945,  72621.16290623,
        65592.52333143,  86678.44205583, 128850.27950464, 178050.75652826,
       149936.19822905, 149936.19822905,  93707.08163064, 128850.27950464,
       192108.03567786, 114793.00035504,  86678.44205583,  72621.16290623,
        86678.44205583, 199136.67525266, 121821.63992984, 121821.63992984,
        79649.80248103, 100735.72120544,  79649.80248103,  65592.52333143,
        86678.44205583,  93707.08163064,  72621.16290623, 135878.91907945,
       178050.75652826,  86678.44205583,  72621.16290623,  93707.08163064,
        72621.16290623, 121821.63992984,  58563.88375663, 100735.72120544,
       234279.87312667, 199136.67525266, 100735.72120544, 213193.95440226,
       156964.83780385, 178050.75652826, 142907.55865425,  86678.44205583,
        72621.16290623, 192108.03567786,  86678.44205583, 142907.55865425,
        65592.52333143, 107764.36078024,  79649.80248103,  79649.80248103,
        86678.44205583,  86678.44205583, 142907.55865425,  65592.52333143,
       135878.91907945, 135878.91907945,  65592.52333143,  86678.44205583,
       121821.63992984, 171022.11695345,  79649.80248103,  93707.08163064,
       128850.27950464, 114793.00035504,  65592.52333143, 135878.91907945,
        65592.52333143, 128850.27950464,  65592.52333143,  86678.44205583,
       213193.95440226, 156964.83780385, 100735.72120544,  93707.08163064,
       121821.63992984, 121821.63992984, 114793.00035504, 156964.83780385,
       107764.36078024,  58563.88375663, 178050.75652826, 121821.63992984,
       142907.55865425, 178050.75652826,  72621.16290623, 192108.03567786,
        86678.44205583, 107764.36078024,  65592.52333143,  72621.16290623,
       192108.03567786,  93707.08163064,  86678.44205583, 178050.75652826,
       114793.00035504,  58563.88375663, 100735.72120544, 121821.63992984,
       185079.39610306, 171022.11695345,  65592.52333143,  72621.16290623,
       121821.63992984,  79649.80248103,  72621.16290623, 135878.91907945,
        93707.08163064,  86678.44205583,  93707.08163064,  65592.52333143,
        93707.08163064,  79649.80248103, 156964.83780385,  93707.08163064,
       114793.00035504,  79649.80248103, 142907.55865425, 100735.72120544,
        86678.44205583, 121821.63992984,  72621.16290623,  93707.08163064,
       121821.63992984, 121821.63992984, 114793.00035504, 107764.36078024,
        65592.52333143, 100735.72120544, 100735.72120544, 114793.00035504,
        65592.52333143,  86678.44205583, 135878.91907945, 114793.00035504,
       135878.91907945, 163993.47737865, 100735.72120544, 114793.00035504,
        79649.80248103, 100735.72120544, 171022.11695345, 107764.36078024,
       163993.47737865, 156964.83780385,  65592.52333143, 114793.00035504,
       107764.36078024,  79649.80248103,  65592.52333143, 114793.00035504,
        79649.80248103, 100735.72120544, 100735.72120544,  65592.52333143,
       156964.83780385, 107764.36078024,  72621.16290623, 171022.11695345,
       163993.47737865, 142907.55865425,  86678.44205583, 163993.47737865,
        65592.52333143, 171022.11695345, 185079.39610306, 128850.27950464,
        58563.88375663, 100735.72120544,  79649.80248103, 185079.39610306,
        72621.16290623,  86678.44205583,  86678.44205583, 163993.47737865,
        65592.52333143, 128850.27950464, 121821.63992984,  79649.80248103,
        86678.44205583,  79649.80248103, 142907.55865425, 220222.59397707,
       149936.19822905, 107764.36078024,  79649.80248103, 283480.35015028,
       142907.55865425,  65592.52333143,  72621.16290623, 100735.72120544,
        65592.52333143, 100735.72120544,  86678.44205583, 135878.91907945,
        86678.44205583,  72621.16290623, 156964.83780385, 220222.59397707,
       100735.72120544,  72621.16290623,  79649.80248103, 121821.63992984,
       171022.11695345, 107764.36078024, 156964.83780385, 142907.55865425,
       135878.91907945, 114793.00035504, 107764.36078024, 128850.27950464,
        86678.44205583,  93707.08163064,  65592.52333143, 185079.39610306,
       220222.59397707, 128850.27950464,  79649.80248103,  72621.16290623,
        72621.16290623, 156964.83780385,  79649.80248103, 121821.63992984,
        72621.16290623, 192108.03567786, 114793.00035504, 156964.83780385,
       114793.00035504,  65592.52333143, 121821.63992984, 227251.23355187,
       171022.11695345,  65592.52333143,  86678.44205583, 114793.00035504,
        72621.16290623, 185079.39610306, 156964.83780385,  65592.52333143,
        58563.88375663,  79649.80248103,  69106.84311883, 114793.00035504,
       142907.55865425,  65592.52333143, 114793.00035504,  79649.80248103,
        86678.44205583, 171022.11695345,  72621.16290623, 142907.55865425,
       107764.36078024,  72621.16290623,  65592.52333143,  79649.80248103,
        65592.52333143, 171022.11695345, 171022.11695345,  65592.52333143,
       135878.91907945, 100735.72120544,  86678.44205583,  79649.80248103,
       128850.27950464, 178050.75652826,  93707.08163064,  93707.08163064,
       220222.59397707,  93707.08163064, 135878.91907945, 114793.00035504,
       114793.00035504, 185079.39610306, 149936.19822905, 149936.19822905,
        79649.80248103,  72621.16290623, 100735.72120544,  93707.08163064,
       128850.27950464, 156964.83780385, 114793.00035504])

In [27]:
lr.coef_

array([7028.6395748])

In [28]:
lr.intercept_

np.float64(58563.8837566266)

In [29]:
from sklearn.metrics import r2_score

In [30]:
r2_score(y_test,y_pred)

0.6690959551629008

In [33]:
import numpy as np
a=np.array([4,7]).reshape(-1,1)
b=lr.predict(a)
b

C:\Users\gavas\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([ 86678.44205583, 107764.36078024])